#!/bin/sh

set -e

# Source: https://gist.github.com/jj1bdx/5746298

# Linux and similar...
CPUS=$(getconf _NPROCESSORS_ONLN 2>/dev/null)
# FreeBSD and similar...
[ -z "$CPUS" ] && CPUS=$(getconf NPROCESSORS_ONLN)
# Solaris and similar...
[ -z "$CPUS" ] && CPUS=$(ksh93 -c 'getconf NPROCESSORS_ONLN')
# Give up...
[ -z "$CPUS" ] && CPUS=1

echo "tail -f $LOG to follow along with the log for troubleshooting!"

# all of the 2> /dev/nulls redirect useless errors (e.g. entering a newline) to devnull

echo ""
echo "Attempting to delete incomplete installations of FM..."
for f in FasterMelee*; do
	if [ -d "${f}" ] && [ ! -d "$f/bin" ]; then
		echo "Found incomplete installation at $f/, deleting."
		rm -rf "$f" # is incomplete if Binaries/ exists, contains config
	fi
done

echo "" # easiest way to print newline while preserving compatibility :P
echo "Would you like to overwrite all of your previous installations? (y/N)"
read -r RESP
if [ "$RESP" = "y" ] 2> /dev/null || [ "$RESP" = "Y" ] 2> /dev/null; then
	echo "Are you sure? This action is not reversible! (y/N)"
	read -r RESP
	if [ "$RESP" = "y" ] 2> /dev/null || [ "$RESP" = "Y" ] 2> /dev/null; then
		rm -rf FasterMelee*/ 2> /dev/null
		echo "Deleted all FM folders!"
	fi
fi

echo ""
echo "Which version of Faster Melee would you like to install? (default: 1)"
echo "1.) 5.66 (Discord default)"
echo "2.) 5.0.3 (SmashLadder default)"
read -r RESP
if [ "$RESP" -eq 2 ] 2> /dev/null; then
 	FMVERSION="5.0.3"
	COMMITHASH="d462ca38724db65d7f92f3edbd16b6657291e420"
	GITCLONELINK="https://github.com/Tinob/Ishiiruka"
else
	FMVERSION="5.66"
	COMMITHASH="cdc00a320232a3a5f023c1aa53d7f4619f322757"
	GITCLONELINK="https://github.com/HannesMann/Ishiiruka"
fi
echo "Installing version $FMVERSION!"
REPLACEFILELINK="https://github.com/Ptomerty/FasterMelee-installer/raw/master/config/$FMVERSION-fmconfig.tar.gz"
FOLDERNAME="FasterMelee-${FMVERSION}_$(date +%F)"
if [ -d "$FOLDERNAME" ]; then
	I=1
	while :
	do
		if [ ! -d "${FOLDERNAME}_${I}" ]; then
			FOLDERNAME="${FOLDERNAME}_${I}"
			break
		fi
		I=$((I+1))
	done
fi
LOG="$(pwd)/$FOLDERNAME/log.txt"

echo ""
echo "Would you like to install rules for your Wii U adapter? (Y/n)"
read -r RESP
if [ ! "$RESP" = "n" ] && [ ! "$RESP" = "N" ]; then
	sudo rm -f /etc/udev/rules.d/51-gcadapter.rules 2> /dev/null # remove even if doesn't exist
	# sudo touch /etc/udev/rules.d/51-gcadapter.rules
	echo 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0337", MODE="0666"' | sudo tee /etc/udev/rules.d/51-gcadapter.rules > /dev/null # pipe to write-protected file, remove STDOUT
	sudo udevadm control --reload-rules
	echo "Rules added!"
fi

echo ""
echo "CPU Threads detected: $CPUS"
echo "How many threads would you like to use to compile? (passed to make as -j flag, default: 1, max: $((CPUS + 1)))"
read -r RESP
if [ "$RESP" -ge 1 ] 2> /dev/null && [ "$RESP" -le $((CPUS + 1)) ] 2> /dev/null; then
	CPUS=$RESP 
else
	CPUS=1
fi
echo "Using $CPUS thread(s)!"

echo ""
mkdir "$FOLDERNAME" && cd "$FOLDERNAME"
echo "Downloading required replacement files..."
wget $REPLACEFILELINK
echo "Extracting..."
tar -xzf "$FMVERSION-fmconfig.tar.gz" && rm "$FMVERSION-fmconfig.tar.gz"	
echo "Cloning repo (may take a while)..."
git clone $GITCLONELINK
cd Ishiiruka
echo "Switching to latest commit..."
git checkout $COMMITHASH >> "$LOG" 2>&1
echo "Adding portable files..."
mkdir build && cd build
mv ../../Binaries .
echo "cmaking..."
cmake .. -DLINUX_LOCAL_DEV=true >>"$LOG" 2>&1
echo "Compiling...(Verbose, will take a while)"
make -j $CPUS 2>>"$LOG" # gets rid of errors as to not cause confusion
echo "Cleaning up..."
rm "$LOG"
cd ../..
mv Ishiiruka/build/Binaries/ bin/
rm -rf Ishiiruka # -f required to remove git history
rm ../launch-faster-melee 2> /dev/null
rm ../launch-fm 2> /dev/null
ln -s "$FOLDERNAME/bin/dolphin-emu" ../launch-fm
echo 'Done! Run ./launch-fm to run the latest installed version!'
echo 'Make sure to unplug and replug your adapter before opening Dolphin for it to function!'
